library(lattice)
library(ggplot2)
library(reshape2)
require(reshape2)
setwd("~/Downloads/bacp/results/")
toy = list.files(pattern="toy")
bacp8 = list.files(pattern="bacp8")
bacp10 = list.files(pattern="bacp10")
bacp12 = list.files(pattern="bacp12")
toyfiles = do.call(rbind, lapply(bacp10, function(x) read.table(x)))
bacp8files = do.call(rbind, lapply(bacp8, function(x) read.table(x)))
bacp10files = do.call(rbind, lapply(bacp10, function(x) read.table(x)))
bacp12files = do.call(rbind, lapply(bacp12, function(x) read.table(x)))
colnames(toyfiles) <- c("Time", "Broken", "Evaluation", "P", "Restart", "Max_iter", "RCL")
colnames(bacp8files) <- c("Time", "Broken", "Evaluation", "P", "Restart", "Max_iter", "RCL")
colnames(bacp10files) <- c("Time", "Broken", "Evaluation", "P", "Restart", "Max_iter", "RCL")
colnames(bacp12files) <- c("Time", "Broken", "Evaluation", "P", "Restart", "Max_iter", "RCL")

require(ggplot2)
boxplot(Evaluation ~ RCL*Restart*Max_iter, data= toyfiles,  col=(c("red","darkgreen","blue")), las=1, horizontal =TRUE, subset = P == 0, main = "Boxplot toy.txt with P=0", xlab = "Evaluation")
legend("topright", title="Length of RCL", c("1","2","3"), fill=(c("red","darkgreen","blue")), horiz=TRUE, cex=0.7, box.lty = 0)
boxplot(Evaluation ~ RCL*Restart*Max_iter, data= toyfiles,  col=(c("red","darkgreen","blue")), las=1, horizontal =TRUE, subset = P == 1, main = "Boxplot toy.txt with P=1", xlab = "Evaluation")
legend("topright", title="Length of RCL", c("1","2","3"), fill=(c("red","darkgreen","blue")), horiz=TRUE, cex=0.7, box.lty = 0)
boxplot(Evaluation ~ RCL*Restart*Max_iter, data= toyfiles,  col=(c("red","darkgreen","blue")), las=1, horizontal =TRUE, subset = P == 2, main = "Boxplot toy.txt with P=2", xlab = "Evaluation") 
legend("topright", title="Length of RCL", c("1","2","3"), fill=(c("red","darkgreen","blue")), horiz=TRUE, cex=0.7, box.lty = 0)

boxplot(Evaluation ~ RCL*Restart*Max_iter, data= bacp8files,  col=(c("red","darkgreen","blue")), las=1, horizontal =TRUE, subset = P == 0, main = "Boxplot bacp8.txt with P=0", xlab = "Evaluation")
legend("topright", title="Length of RCL", c("1","2","3"), fill=(c("red","darkgreen","blue")), horiz=TRUE, cex=0.7, box.lty = 0)
boxplot(Evaluation ~ RCL*Restart*Max_iter, data= bacp8files,  col=(c("red","darkgreen","blue")), las=1, horizontal =TRUE, subset = P == 1, main = "Boxplot bacp8.txt with P=1", xlab = "Evaluation")
legend("topright", title="Length of RCL", c("1","2","3"), fill=(c("red","darkgreen","blue")), horiz=TRUE, cex=0.7, box.lty = 0)
boxplot(Evaluation ~ RCL*Restart*Max_iter, data= bacp8files,  col=(c("red","darkgreen","blue")), las=1, horizontal =TRUE, subset = P == 2, main = "Boxplot bacp8.txt with P=2", xlab = "Evaluation") 
legend("topright", title="Length of RCL", c("1","2","3"), fill=(c("red","darkgreen","blue")), horiz=TRUE, cex=0.7, box.lty = 0)

boxplot(Evaluation ~ RCL*Restart*Max_iter, data= bacp10files,  col=(c("red","darkgreen","blue")), las=1, horizontal =TRUE, subset = P == 0, main = "Boxplot bacp10.txt with P=0", xlab = "Evaluation")
legend("topright", title="Length of RCL", c("1","2","3"), fill=(c("red","darkgreen","blue")), horiz=TRUE, cex=0.7, box.lty = 0)
boxplot(Evaluation ~ RCL*Restart*Max_iter, data= bacp10files,  col=(c("red","darkgreen","blue")), las=1, horizontal =TRUE, subset = P == 1, main = "Boxplot bacp10.txt with P=1", xlab = "Evaluation")
legend("topright", title="Length of RCL", c("1","2","3"), fill=(c("red","darkgreen","blue")), horiz=TRUE, cex=0.7, box.lty = 0)
boxplot(Evaluation ~ RCL*Restart*Max_iter, data= bacp10files,  col=(c("red","darkgreen","blue")), las=1, horizontal =TRUE, subset = P == 2, main = "Boxplot bacp10.txt with P=2", xlab = "Evaluation") 
legend("topright", title="Length of RCL", c("1","2","3"), fill=(c("red","darkgreen","blue")), horiz=TRUE, cex=0.7, box.lty = 0)

boxplot(Evaluation ~ RCL*Restart*Max_iter, data= bacp12files,  col=(c("red","darkgreen","blue")), las=1, horizontal =TRUE, subset = P == 0, main = "Boxplot bacp12.txt with P=0", xlab = "Evaluation")
legend("topright", title="Length of RCL", c("1","2","3"), fill=(c("red","darkgreen","blue")), horiz=TRUE, cex=0.7, box.lty = 0)
boxplot(Evaluation ~ RCL*Restart*Max_iter, data= bacp12files,  col=(c("red","darkgreen","blue")), las=1, horizontal =TRUE, subset = P == 1, main = "Boxplot bacp12.txt with P=1", xlab = "Evaluation")
legend("topright", title="Length of RCL", c("1","2","3"), fill=(c("red","darkgreen","blue")), horiz=TRUE, cex=0.7, box.lty = 0)
boxplot(Evaluation ~ RCL*Restart*Max_iter, data= bacp12files,  col=(c("red","darkgreen","blue")), las=1, horizontal =TRUE, subset = P == 2, main = "Boxplot bacp12.txt with P=2", xlab = "Evaluation") 
legend("topright", title="Length of RCL", c("1","2","3"), fill=(c("red","darkgreen","blue")), horiz=TRUE, cex=0.7, box.lty = 0)
